rails/inviado-on-rails/config/routes.rb
Rails.application.routes.draw do
  resources :featurings
  resources :features
  resources :taggings
  resources :commentings
  resources :linkings
  resources :searchings
  resources :comments
  resources :tags
  resources :searchresults
  resources :links
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  get "/graphql", to: "graphql#execute"
  resources :organizations
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :memberships
  resources :members
  resources :articles

  get 'index/new'
  get 'index/create'
  get 'welcome/index'

  # administration
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
end

rails/inviado-on-rails/app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

rails/inviado-on-rails/app/models/article.rb
class Article < ApplicationRecord
end

rails/inviado-on-rails/app/models/comment.rb
class Comment < ApplicationRecord
  has_many :commentings, dependent: :destroy
  has_many :organizations, through: :commentings, source: :commentable, source_type: 'Organization'

  accepts_nested_attributes_for :organizations
end

rails/inviado-on-rails/app/models/commenting.rb
class Commenting < ApplicationRecord
  belongs_to :comment
  belongs_to :commentable, polymorphic: true
end

rails/inviado-on-rails/app/models/feature.rb
class Feature < ApplicationRecord
  has_many :featurings, dependent: :destroy
  has_many :organizations, through: :featurings, source: :featurable, source_type: 'Organization'

  accepts_nested_attributes_for :organizations
end

rails/inviado-on-rails/app/models/featuring.rb
class Featuring < ApplicationRecord
  belongs_to :feature
  belongs_to :featurable, polymorphic: true
end

rails/inviado-on-rails/app/models/link.rb
class Link < ApplicationRecord
  has_many :linkings, dependent: :destroy
  has_many :organizations, through: :linkings, source: :linkable, source_type: 'Organization'

  accepts_nested_attributes_for :organizations
end

rails/inviado-on-rails/app/models/linking.rb
class Linking < ApplicationRecord
  belongs_to :link
  belongs_to :linkable, polymorphic: true
end

rails/inviado-on-rails/app/models/member.rb
class Member < ApplicationRecord
  has_many :memberships, dependent: :destroy
  has_many :organizations, through: :memberships, source: :membershipable, source_type: 'Organization'

  accepts_nested_attributes_for :organizations
end

rails/inviado-on-rails/app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :member
  belongs_to :membershipable, polymorphic: true
end

rails/inviado-on-rails/app/models/organization.rb
class Organization < ApplicationRecord
  # polymorphic associations
  include Linkable
  include Searchable
  include Taggable
  include Commentable
  include Featurable
  include Membershipable

  # helper
  include OrganizationHelper

  # attachments
  has_many_attached :screenshots
  has_many_attached :thumbs
end

rails/inviado-on-rails/app/models/searching.rb
class Searching < ApplicationRecord
  belongs_to :searchresult
  belongs_to :searchable, polymorphic: true
end

rails/inviado-on-rails/app/models/searchresult.rb
class Searchresult < ApplicationRecord
  has_many :searchings, dependent: :destroy
  has_many :organizations, through: :searchings, source: :searchable, source_type: 'Organization'

  accepts_nested_attributes_for :organizations
end

rails/inviado-on-rails/app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings, dependent: :destroy
  has_many :organizations, through: :taggings, source: :taggable, source_type: 'Organization'

  accepts_nested_attributes_for :organizations
end

rails/inviado-on-rails/app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :taggable, polymorphic: true
end

rails/inviado-on-rails/app/controllers/links_controller.rb
class LinksController < InheritedResources::Base

  private

    def link_params
      params.require(:link).permit(:title, :target, :uri, :description, :source, :raw)
    end

end

rails/inviado-on-rails/app/helpers/articles_helper.rb
module ArticlesHelper
end

rails/inviado-on-rails/app/helpers/comments_helper.rb
module CommentsHelper
end

rails/inviado-on-rails/app/helpers/index_helper.rb
module IndexHelper
end

rails/inviado-on-rails/app/helpers/links_helper.rb
module LinksHelper
end

rails/inviado-on-rails/app/helpers/members_helper.rb
module MembersHelper
end

rails/inviado-on-rails/app/helpers/tags_helper.rb
module TagsHelper
end

rails/inviado-on-rails/app/helpers/welcome_helper.rb
module WelcomeHelper
end

rails/inviado-on-rails/app/views/links/_form.html.erb
<%= form_with(model: link, local: true) do |form| %>
  <% if link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
        <% link.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :target %>
    <%= form.text_field :target %>
  </div>

  <div class="field">
    <%= form.label :uri %>
    <%= form.text_field :uri %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :source %>
    <%= form.text_field :source %>
  </div>

  <div class="field">
    <%= form.label :raw %>
    <%= form.text_field :raw %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

rails/inviado-on-rails/app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

rails/inviado-on-rails/app/views/links/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Links</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Target</th>
      <th>Uri</th>
      <th>Description</th>
      <th>Source</th>
      <th>Raw</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @links.each do |link| %>
      <tr>
        <td><%= link.title %></td>
        <td><%= link.target %></td>
        <td><%= link.uri %></td>
        <td><%= link.description %></td>
        <td><%= link.source %></td>
        <td><%= link.raw %></td>
        <td><%= link_to 'Show', link %></td>
        <td><%= link_to 'Edit', edit_link_path(link) %></td>
        <td><%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Link', new_link_path %>

rails/inviado-on-rails/app/views/links/new.html.erb
<h1>New Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Back', links_path %>

rails/inviado-on-rails/app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @link.title %>
</p>

<p>
  <strong>Target:</strong>
  <%= @link.target %>
</p>

<p>
  <strong>Uri:</strong>
  <%= @link.uri %>
</p>

<p>
  <strong>Description:</strong>
  <%= @link.description %>
</p>

<p>
  <strong>Source:</strong>
  <%= @link.source %>
</p>

<p>
  <strong>Raw:</strong>
  <%= @link.raw %>
</p>

<%= link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>